plugins {
    id 'com.github.johnrengelman.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    modImplementation "net.anvian.anvianslib:anvianslib-fabric-1.19:${rootProject.anvianslib_version}"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = "${base.archivesName.get()}-${rootProject.minecraft_version}"
            from components.java
        }
    }
    repositories {
        maven {
            name = "Reposilite"
            url = uri(version.toString().endsWith("SNAPSHOT") ?
                    "https://maven.anvian.net/snapshots" :
                    "https://maven.anvian.net/releases")
            credentials {
                username = (project.findProperty("reposilite.user") as String) ?: System.getenv("REPOSILITE_USER")
                password = (project.findProperty("reposilite.token") as String) ?: System.getenv("REPOSILITE_TOKEN")
            }
        }
    }
}
