modLoader="javafml"
loaderVersion="[45,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/anviaan/SimpleMango/issues"
[[mods]]
modId="simplemango"
version="1.3.3"
displayName="SimpleMango Mod"
updateJSONURL="https://anvian-page.netlify.app/forge/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-mango"
logoFile="assets/simplemango/icon.png"
authors="anvian"
credits="PinhaColada2222"
description="Adds a food Mango!, which has a new type of wood and a new fruit, new trades and more."
[[dependencies.simplemango]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplemango]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
